from email.mime import image
import json
import os
import random
from sqlalchemy.orm import Session
import time
from app.models.category import Categories
from app.models.product import Product
from app.models.product_image import ProductImage
from app.models.supplier import Supplier
from app.models.product_type import ProductType
from app.models.country import Country
from app.utils.string_utils import generate_slug




class InitialDataImportSeeder:

    def seed(self, db: Session):
        supplier_ids = [s.id for s in db.query(Supplier.id).all()]
        product_type_ids = [pt.id for pt in db.query(ProductType.id).all()]
        country_ids = [c.id for c in db.query(Country.id).all()]
        json_file_path = os.path.join(os.path.dirname(__file__), "raw_data/category_data.json")

        if not os.path.exists(json_file_path):
            print(f"❌ JSON file not found at: {json_file_path}")
            return

        with open(json_file_path, 'r') as file:
            data = json.load(file)

        main_cat_count = 0
        sub_cat_count = 0
        product_count = 0
        failed_categories = []

        for main_cat_data in data:
            try:
                # Each main category gets its own transaction (SAVEPOINT)
                db.begin_nested()

                # 1. Create Main Category
                main_category = Categories(
                    name=main_cat_data["name"],
                    slug=generate_slug(main_cat_data["name"]),
                    image=main_cat_data["image"],
                    description=f"Explore our wide range of {main_cat_data['name']}",
                    is_active=True,
                    parent_id=None  # Top level
                )
                db.add(main_category)
                db.flush()  # Flush to generate main_category.id
                main_cat_count += 1

                for sub_key, sub_cat_data in enumerate(main_cat_data.get("subcategories", [])):
                    slug=generate_slug(sub_cat_data["name"])
                    if db.query(Categories).filter(Categories.slug == slug).first():
                        timestamp = int(time.time())
                        slug = f"{slug}-{timestamp}-{sub_key}"
                    # 2. Create Subcategory
                    subcategory = Categories(
                        name=sub_cat_data["name"],
                        slug=slug,
                        image=sub_cat_data["image"],
                        description=f"High quality {sub_cat_data['name']}",
                        is_active=True,
                        parent_id=main_category.id  # Link to Main Category
                    )
                    db.add(subcategory)
                    db.flush()  # Flush to generate subcategory.id
                    sub_cat_count += 1

                    # for key, product_name in sub_cat_data.get("products", []):
                    for key, product_data in enumerate(sub_cat_data.get("products", [])):
                        product_name = product_data["name"]
                        product_images = product_data.get("images", [])

                        slug=generate_slug(product_name)
                         # Check if slug already exists, append timestamp if so
                        if db.query(Product).filter(Product.slug == slug).first():
                            timestamp = int(time.time())
                            slug = f"{slug}-{timestamp}-{key}"
                        # 3. Create Product
                        product = Product(
                            title=product_name,
                            slug=slug,
                            description=f"Detailed description for {product_name}. "
                                        f"This is dummy text generated by the seeder.",
                            short_desc=f"Best {product_name} in the market.",
                            currency="USD",
                            price=round(random.uniform(5.0, 150.0), 2),
                            price_per_measurement="1 piece",
                            min_order=random.choice([1, 10, 50, 100]),
                            category_id=subcategory.id,  # Link to Subcategory
                            id_recomended=random.choice([True, False]),
                            country_id=random.choice(country_ids) if country_ids else None,
                            supplier_id=random.choice(supplier_ids),
                            product_type_id=random.choice(product_type_ids) if product_type_ids else None,
                        )
                        db.add(product)
                        db.flush()

                        # 4. Create Product Images
                        for idx, img_url in enumerate(product_images):
                            product_image = ProductImage(
                                product_id=product.id,
                                image=img_url,
                                is_preview=(idx == 0)
                            )
                            db.add(product_image)

                        product_count += 1

                # Commit this main category's savepoint
                db.commit()
                print(f"   ✅ Imported: {main_cat_data['name']}")

            except Exception as e:
                db.rollback()
                failed_categories.append(main_cat_data["name"])
                print(f"   ❌ Failed to import '{main_cat_data['name']}': {e}")

        print(f"\n{'='*50}")
        print(f"✅ Database seeding completed!")
        print(f"   📁 Main Categories: {main_cat_count}")
        print(f"   📂 Subcategories:    {sub_cat_count}")
        print(f"   📦 Products:         {product_count}")
        if failed_categories:
            print(f"   ⚠️  Failed:          {', '.join(failed_categories)}")

    def run(self, db: Session):
        self.seed(db=db)
