"""add deleted_at to category

Revision ID: 0eb252bd61c8
Revises: 29fb41c0374e
Create Date: 2026-02-16 22:36:55.646757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb252bd61c8'
down_revision: Union[str, Sequence[str], None] = '29fb41c0374e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.execute("ALTER TABLE categories ADD COLUMN deleted_at DATETIME NULL AFTER updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
