"""add fields to supplier table

Revision ID: 1e04a8cad5e3
Revises: 34964aefb6ec
Create Date: 2026-05-01 08:52:04.579763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e04a8cad5e3'
down_revision: Union[str, Sequence[str], None] = '34964aefb6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'details')
    # ### end Alembic commands ###
