"""add fields to enquiry table

Revision ID: 2bf21247cf3a
Revises: d213cd6ec090
Create Date: 2026-04-18 08:52:44.241017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf21247cf3a'
down_revision: Union[str, Sequence[str], None] = 'd213cd6ec090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('enquiries', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('enquiries', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('enquiries', sa.Column('status', sa.String(length=255), server_default='Pending', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'status')
    op.drop_column('enquiries', 'phone')
    op.drop_column('enquiries', 'email')
    op.drop_column('enquiries', 'name')
    # ### end Alembic commands ###
