"""add country_id fields to enquiry table

Revision ID: 34964aefb6ec
Revises: 870102d1b590
Create Date: 2026-04-26 10:17:32.118917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34964aefb6ec'
down_revision: Union[str, Sequence[str], None] = '870102d1b590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enquiries', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.drop_column('enquiries', 'country_id')
    # ### end Alembic commands ###
