"""add is recomended to products table

Revision ID: 7759d9b8f70b
Revises: 29ab89945a2e
Create Date: 2026-03-09 09:20:45.905979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7759d9b8f70b'
down_revision: Union[str, Sequence[str], None] = '29ab89945a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id_recomended', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'id_recomended')
    # ### end Alembic commands ###
