"""add country_flag to countries

Revision ID: 780d1abdf2e2
Revises: 0a4fcd063c4e
Create Date: 2026-03-03 20:09:08.956083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780d1abdf2e2'
down_revision: Union[str, Sequence[str], None] = '0a4fcd063c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('country_flag', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'country_flag')
    # ### end Alembic commands ###
