"""create enquiry and files table

Revision ID: 899e71392028
Revises: 9bf721124260
Create Date: 2026-03-18 23:06:27.906482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '899e71392028'
down_revision: Union[str, Sequence[str], None] = '9bf721124260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason_for_contacting', sa.Text(), nullable=False),
    sa.Column('request_title', sa.Text(), nullable=True),
    sa.Column('delivery_location', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('forward_to_other', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  '), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry_files')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
