"""add enquiry_number to enquiries tble

Revision ID: 927dbbe33816
Revises: 2bf21247cf3a
Create Date: 2026-04-18 11:14:20.275804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927dbbe33816'
down_revision: Union[str, Sequence[str], None] = '2bf21247cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('enquiry_number', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'enquiries', ['enquiry_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiries', type_='unique')
    op.drop_column('enquiries', 'enquiry_number')
    # ### end Alembic commands ###
