"""add country_code to country table

Revision ID: 9bf721124260
Revises: fa3388c1eb8d
Create Date: 2026-03-14 17:29:37.216109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf721124260'
down_revision: Union[str, Sequence[str], None] = 'fa3388c1eb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('country_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'countries', ['country_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'country_code')
    # ### end Alembic commands ###
