"""update reason_for_contacting nullable , add is_quote_form to enquiries table 

Revision ID: a595f609793d
Revises: 899e71392028
Create Date: 2026-03-21 17:14:19.908733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a595f609793d'
down_revision: Union[str, Sequence[str], None] = '899e71392028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'country_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('enquiries', sa.Column('is_quote_form', sa.Boolean(), server_default='0', nullable=True, comment='submitted from quote form = 1 and join enquery_supplier_types table, submitted from contact supplier button = 0 and use supplier_id colum'))
    op.alter_column('enquiries', 'reason_for_contacting',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('enquiries', 'supplier_id',
               existing_type=mysql.INTEGER(),
               comment='submitted from contact supplier button will have this value, submitted from quote form will have null value',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enquiries', 'supplier_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='submitted from contact supplier button will have this value, submitted from quote form will have null value',
               existing_nullable=True)
    op.alter_column('enquiries', 'reason_for_contacting',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('enquiries', 'is_quote_form')
    op.alter_column('countries', 'country_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
