"""create enquiry_supplier table

Revision ID: d0d54c86e902
Revises: a595f609793d
Create Date: 2026-03-21 17:15:32.373286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d54c86e902'
down_revision: Union[str, Sequence[str], None] = 'a595f609793d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_suppliers_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('supplier_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.ForeignKeyConstraint(['supplier_type_id'], ['supplier_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry_suppliers_types')
    # ### end Alembic commands ###
