"""add is_accept_terms to supplier table

Revision ID: d213cd6ec090
Revises: 1038853b5b57
Create Date: 2026-04-02 23:21:12.287902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd213cd6ec090'
down_revision: Union[str, Sequence[str], None] = '1038853b5b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('is_accept_terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_accept_terms')
    # ### end Alembic commands ###
