"""add business_sector and address2 to supplier table 

Revision ID: d9ec21e9ec8f
Revises: d0d54c86e902
Create Date: 2026-03-26 22:20:59.661483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ec21e9ec8f'
down_revision: Union[str, Sequence[str], None] = 'd0d54c86e902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('address_two', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('business_sector', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'business_sector')
    op.drop_column('suppliers', 'address_two')
    # ### end Alembic commands ###
