"""add business_doc to suppliers table

Revision ID: fa3388c1eb8d
Revises: 7759d9b8f70b
Create Date: 2026-03-13 21:03:43.074771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3388c1eb8d'
down_revision: Union[str, Sequence[str], None] = '7759d9b8f70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('busines_doc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'busines_doc')
    # ### end Alembic commands ###
